### ISSUE TITLE
Show markers at lower zoom level

### ISSUE THREAD

**Issue by Cj-Malone** [gregrs-uk/fhodot#1]
Hey, the new version is looking good. However I hope some functionality is not lost in the transition.

In the previous version the district page provided a good overview on how a specific area was mapped, and highlighted issues and suggested matches. The new version doesn't highlight issues or show suggested matches until being quite zoomed in, making it harder to match and monitor a large area. In the old tool I felt I could easily monitor/maintain all of the Isle of Wight, but I don't think I could do that with the new tool. I think showing more data at a lower zoom would be one way to help.

**Comment by gregrs-uk** [comment]
Thanks @Cj-Malone.

@rjw62 has also requested this via email:

>  I don't know if there's anything you can do about this, but I miss the ability to see a whole district (or at least a wider area) to look for new suggested matches. I'd periodically check the districts near me for mismatches and new suggestions to try to keep things up to date. I don't think it's possible to do that now without manually scrolling around a lot.

The current limit on showing markers was chosen to allow data to load quickly from the API. The FHRS, OSM and distant data sources load pretty quickly, but the suggested matches data source takes longer as the server only looks for matches on demand rather than the suggested matches being cached.

Setting a lower limit for the zoom level at which markers appear for the other layers apart from suggested matches shouldn't be too difficult.

Pre-calculating suggested matches could be one way forward to allow them to display at higher zoom levels would be better, although this would be more work.

Not sure whether I'll have time to implement these in the near future but I will certainly keep them in mind as priorities. I'll also try to keep the old comparison tool running in the meantime.

**Comment by gregrs-uk** [comment]
https://github.com/gregrs-uk/fhodot/commit/c6dd01f8160f64567a22ef2b974ad059bcc1f323 and https://github.com/gregrs-uk/fhodot/commit/3f032cb85207d0125bae6b1da3d11b541df016f5 improve performance for the suggested matches view. This should make it possible to allow markers to display at a lower zoom level in some areas, but first I'd like to add a check for data quantity to avoid trying to load large quantities of data in some urban areas e.g. central London.

**Comment by Cj-Malone** [comment]
Thank you, this certainly feels better.
