### ISSUE TITLE
Filter FHRS data to remove old establishments

### ISSUE THREAD

**Issue by Cj-Malone** [gregrs-uk/fhodot#2]
There are more than a few establishments still in the FHRS dataset after they have closed [eg](https://ratings.food.gov.uk/business/en-GB/541823). Old inspection dates can be an indicator for that, perhaps they shouldn't be shown.

Another option would be to make the inspection date more viable to make mappers aware. Maybe show it in the blue boxes that show the FHRS data.

**Comment by Cj-Malone** [comment]
[This](https://www.highspeedtraining.co.uk/hub/how-often-are-food-hygiene-inspections/) suggests highly rated are surveyed less often and 5 star establishments can be over 2 years between inspections. I think doubling that to 4 years would be a safe age to filter, although I haven't queried the FHRS data to check.

**Comment by gregrs-uk** [comment]
Rating dates are now displayed to aid mappers, and are highlighted yellow if not within the last 5 years. (Between 90% and 95% of establishments have been inspected in the last 5 years.)

I don't think we should filter by rating date as looking at the data there are plenty of valid establishments which haven't been inspected for a long while (e.g. especially church/village halls), and I would imagine there will be quite a few establishments inspected within the last few years that have since closed.

Some further analysis of the age of ratings below.

![histogram](https://user-images.githubusercontent.com/7353938/113488463-4525dc80-94b6-11eb-9fac-4cfda3ef2a4a.png)

```
percentile age_days age_years
      0.5       709       1.9
      0.75     1009       2.8
      0.9      1496       4.1
      0.95     2236       6.1
      0.99     4196      11.5
```
