### ISSUE TITLE
Certain relations are not properly loaded in JOSM

### ISSUE THREAD

**Issue by inan-hira** [gregrs-uk/fhodot#31]
I don't know the exact reason, but certain relations are not loaded when you click on the "Add tags in JOSM" link.

### Example

I'd noticed this before a couple of times, but didn't think about creating a bug report at that time. [Chandlers Field Primary School](https://gregrs.dev.openstreetmap.org/fhodot/?lat=51.39815&lon=-0.37024&zoom=19&layer=suggest) cannot be loaded in JOSM. I say cannot be loaded, but the data is imported. However, the relation is not displayed at all. The whole data layer is empty. Please see the screenshots:

Tag selection prompt:
[<img width="500" alt="image" src="https://github.com/user-attachments/assets/4757b0ab-aa1a-4783-ba54-8cb68cab030a">](https://github.com/user-attachments/assets/4757b0ab-aa1a-4783-ba54-8cb68cab030a)

After the tags are added:
[<img width="500" alt="image" src="https://github.com/user-attachments/assets/457dea64-24b4-426b-86e3-b885caaebc62">](https://github.com/user-attachments/assets/457dea64-24b4-426b-86e3-b885caaebc62)

### To replicate

1. Delete all data layers in JOSM
2. Navigate to the [example](https://gregrs.dev.openstreetmap.org/fhodot/?lat=51.39815&lon=-0.37024&zoom=19&layer=suggest).
3. Click "Add tags in JOSM" link.

**Comment by rjw62** [comment]
I think the links from FHODOT do work and you can use them to add the relevant tags as you would with any other object. The object is selected, and you can see the tags in JOSM, but there's no geometry selected in the main view.

This is because the behaviour of JOSM when asked to load a single relation is to just load the data for the relation object, and not also load any of its (node or way) members. The geometry is only stored on the nodes. This behaviour is in contrast to what happens when you load a single way in JOSM - when JOSM will automatically also load all the nodes.

If FHODOT is using the JOSM remote control command I think it is, then it looks like it might be possible to instruct JOSM to also load the relation's members, by adding relation_members=true to the load_object call. See https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#load_object . I think it would make things more usable if this could be done, and the core functionality still works.
